SELECT M.SYS_ID AS 應用系統
     , M.FUN_CONTROLLER_ID AS ControllerName
  , FUN_ACTION_NAME AS ActionName
     , G.FUN_GROUP_ZH_TW AS 功能群組
     , dbo.FN_GET_NMID(FUN_ACTION_NAME, FUN_NM_ZH_TW) AS 功能名稱 
FROM SYS_SYSTEM_FUN M
LEFT JOIN SYS_SYSTEM_FUN_GROUP G
ON G.SYS_ID = M.SYS_ID
AND G.FUN_CONTROLLER_ID = M.FUN_CONTROLLER_ID
WHERE M.SYS_ID in ('GITAP','FNAP')
ORDER BY M.SYS_ID, M.SORT_ORDER