--業務作業
SELECT F.SYS_ID AS 應用系統
     , dbo.FN_GET_NMID(F.FUN_MENU, M.FUN_MENU_NM_ZH_TW) AS 選單名稱
     , dbo.FN_GET_NMID(N.FUN_ACTION_NAME, N.FUN_NM_ZH_TW) AS 選單內容
     , F.FUN_CONTROLLER_ID AS ControllerName
	 , F.FUN_ACTION_NAME AS ActionName 
FROM SYS_SYSTEM_MENU_FUN F 
JOIN SYS_SYSTEM_FUN_MENU M ON F.FUN_MENU_SYS_ID=M.SYS_ID AND F.FUN_MENU=M.FUN_MENU
JOIN SYS_SYSTEM_FUN N ON N.SYS_ID = F.SYS_ID
AND F.FUN_CONTROLLER_ID = N.FUN_CONTROLLER_ID
AND F.FUN_ACTION_NAME = N.FUN_ACTION_NAME
WHERE F.SYS_ID IN ('TOURAP','ORDRAP', 'TKTAP', 'GITAP')
AND (F.FUN_MENU = 'Sales')
ORDER BY F.SYS_ID, F.FUN_ACTION_NAME 

--團產作業
SELECT F.SYS_ID AS 應用系統
     , dbo.FN_GET_NMID(F.FUN_MENU, M.FUN_MENU_NM_ZH_TW) AS 選單名稱
     , dbo.FN_GET_NMID(N.FUN_ACTION_NAME, N.FUN_NM_ZH_TW) AS 選單內容
     , F.FUN_CONTROLLER_ID AS ControllerName
	 , F.FUN_ACTION_NAME AS ActionName 
FROM SYS_SYSTEM_MENU_FUN F 
JOIN SYS_SYSTEM_FUN_MENU M ON F.FUN_MENU_SYS_ID=M.SYS_ID AND F.FUN_MENU=M.FUN_MENU
JOIN SYS_SYSTEM_FUN N ON N.SYS_ID = F.SYS_ID
AND F.FUN_CONTROLLER_ID = N.FUN_CONTROLLER_ID
AND F.FUN_ACTION_NAME = N.FUN_ACTION_NAME
WHERE F.SYS_ID = 'GITAP'
AND F.FUN_MENU = 'GIT'
ORDER BY F.SYS_ID, F.FUN_ACTION_NAME 

--費用支單
SELECT F.SYS_ID AS 應用系統
     , dbo.FN_GET_NMID(F.FUN_MENU, M.FUN_MENU_NM_ZH_TW) AS 選單名稱
     , dbo.FN_GET_NMID(N.FUN_ACTION_NAME, N.FUN_NM_ZH_TW) AS 選單內容
     , F.FUN_CONTROLLER_ID AS ControllerName
	 , F.FUN_ACTION_NAME AS ActionName 
FROM SYS_SYSTEM_MENU_FUN F 
JOIN SYS_SYSTEM_FUN_MENU M ON F.FUN_MENU_SYS_ID=M.SYS_ID AND F.FUN_MENU=M.FUN_MENU
JOIN SYS_SYSTEM_FUN N ON N.SYS_ID = F.SYS_ID
AND F.FUN_CONTROLLER_ID = N.FUN_CONTROLLER_ID
AND F.FUN_ACTION_NAME = N.FUN_ACTION_NAME
WHERE F.SYS_ID = 'FNAP'
ORDER BY F.SYS_ID, F.FUN_ACTION_NAME 





SELECT FUN_MENU_NM_ZH_TW AS '功能選單'
, FN.SYS_ID +'-'+(SELECT SYS_NM_ZH_TW FROM SYS_SYSTEM_MAIN WHERE SYS_ID=FN.SYS_ID) AS '系統'
, FN.SUB_SYS_ID +'-'+(SELECT SYS_NM_ZH_TW FROM SYS_SYSTEM_SUB WHERE PARENT_SYS_ID=FN.SYS_ID AND  SYS_ID=FN.SUB_SYS_ID) AS '子系統'
, (SELECT FUN_NM_ZH_TW FROM SYS_SYSTEM_FUN WHERE SYS_ID=FN.SYS_ID AND FUN_CONTROLLER_ID=FN.FUN_CONTROLLER_ID AND FUN_ACTION_NAME=FN.FUN_ACTION_NAME)+'('+FN.FUN_CONTROLLER_ID+'/'+FN.FUN_ACTION_NAME+')' AS '功能名稱'
FROM SYS_SYSTEM_FUN_MENU FNM
JOIN SYS_SYSTEM_MENU_FUN MFN
ON FNM.SYS_ID = MFN.FUN_MENU_SYS_ID
AND FNM.FUN_MENU = MFN.FUN_MENU
JOIN SYS_SYSTEM_FUN FN
ON MFN.SYS_ID = FN.SYS_ID
AND MFN.FUN_CONTROLLER_ID = FN.FUN_CONTROLLER_ID
AND MFN.FUN_ACTION_NAME = FN.FUN_ACTION_NAME
AND FN.IS_DISABLE = 'N'
AND FNM.IS_DISABLE = 'N'
WHERE FUN_MENU_NM_ZH_TW IN ('團產作業','費用支單','業務作業')
ORDER BY FUN_MENU_NM_ZH_TW, FN.SYS_ID, FN.SUB_SYS_ID