--新增流程
 SELECT F.IS_START_FUN 
   FROM SYS_SYSTEM_WF_FLOW F 
  WHERE F.SYS_ID = 'PUBAP' 
    AND F.WF_FLOW_ID = 'SignForm' 
    AND F.WF_FLOW_VER = '001' 

SELECT * FROM SYS_SYSTEM_WF_FLOW

--查起始功能URL (PUBAP	WorkFlow	SignFormDetail)
SELECT F.SUB_SYS_ID AS SubSysID 
     , S.FUN_CONTROLLER_ID AS FunControllerID 
     , S.FUN_ACTION_NAME AS FunActionName 
  FROM SYS_SYSTEM_WF_NODE S 
  JOIN SYS_SYSTEM_WF_NEXT N 
    ON S.SYS_ID = N.SYS_ID 
   AND S.WF_FLOW_ID = N.WF_FLOW_ID 
   AND S.WF_FLOW_VER = N.WF_FLOW_VER 
   AND S.WF_NODE_ID = N.NEXT_WF_NODE_ID 
  JOIN SYS_SYSTEM_FUN F 
    ON S.FUN_SYS_ID = F.SYS_ID 
   AND S.FUN_CONTROLLER_ID = F.FUN_CONTROLLER_ID 
   AND S.FUN_ACTION_NAME = F.FUN_ACTION_NAME 
 WHERE N.SYS_ID = 'PUBAP' 
   AND N.WF_FLOW_ID = 'SignForm' 
   AND N.WF_FLOW_VER = '001' 
   AND N.WF_NODE_ID = 'START'

SELECT * FROM SYS_SYSTEM_WF_NEXT    
SELECT * FROM SYS_SYSTEM_WF_NODE
SELECT * FROM SYS_SYSTEM_WF_FLOW


DECLARE @SYS_ID VARCHAR(12);
DECLARE @FLOW_ID VARCHAR(50); 
DECLARE @FLOW_VER VARCHAR(3); 
DECLARE @LOT NVARCHAR(50);
DECLARE @SUBJECT NVARCHAR(150); 
DECLARE @NODE_NO CHAR(3);
DECLARE @USER_ID VARCHAR(20); 
DECLARE @UPD_USER_ID VARCHAR(20);
DECLARE @RESULT VARCHAR(50) = 'Success';
DECLARE @ERROR_LINE INT;
DECLARE @ERROR_NUMBER INT;
DECLARE @ERROR_MESSAGE NVARCHAR(4000);
DECLARE @TODAY_YEAR CHAR(4) = CAST(YEAR(GETDATE()) AS CHAR); 
DECLARE @TODAY_YMD CHAR(8) = dbo.FN_GET_SYSDATE(NULL); 
DECLARE @NOW_DATETIME CHAR(17) = @TODAY_YMD + dbo.FN_GET_SYSTIME(NULL); 
DECLARE @IS_START_SIG CHAR(1) = NULL; 
DECLARE @WF_NO CHAR(14); 
DECLARE @WF_NODE_ID VARCHAR(50); 
DECLARE @REMARK_NO CHAR(3); 

--取得起始節點 取得ApplySignForm
SELECT DISTINCT @WF_NODE_ID = N.WF_NODE_ID 
  FROM SYS_SYSTEM_WF_FLOW F 
  JOIN SYS_SYSTEM_WF_NODE N 
    ON F.SYS_ID = N.SYS_ID 
   AND F.WF_FLOW_ID = N.WF_FLOW_ID 
   AND F.WF_FLOW_VER = N.WF_FLOW_VER 
   AND N.IS_FIRST = 'Y' 
  JOIN SYS_SYSTEM_ROLE_FLOW R 
    ON F.SYS_ID = R.SYS_ID 
   AND F.WF_FLOW_ID = R.WF_FLOW_ID 
   AND F.WF_FLOW_VER = R.WF_FLOW_VER 
 WHERE F.SYS_ID = 'PUBAP' 
   AND F.WF_FLOW_ID = 'SignForm' 
   AND F.WF_FLOW_VER = '001' 
   AND F.ENABLE_DATE <= '20171116' 
   AND ISNULL(F.DISABLE_DATE, '99999999') > '20171116' ; 
SELECT @WF_NODE_ID

--確認建FLOW者有沒有NODE設定的系統角色
SELECT M.* 
  FROM SYS_SYSTEM_WF_NODE M 
  JOIN SYS_SYSTEM_ROLE_NODE R 
    ON M.SYS_ID = R.SYS_ID 
   AND M.WF_FLOW_ID = R.WF_FLOW_ID 
   AND M.WF_FLOW_VER = R.WF_FLOW_VER 
   AND M.WF_NODE_ID = R.WF_NODE_ID 
  JOIN SYS_USER_SYSTEM_ROLE U 
    ON U.USER_ID = 'D223' 
   AND R.SYS_ID = U.SYS_ID 
   AND R.ROLE_ID = U.ROLE_ID 
 WHERE M.SYS_ID = 'PUBAP' 
   AND M.WF_FLOW_ID = 'SignForm' 
   AND M.WF_FLOW_VER = '001' 
   AND M.WF_NODE_ID = 'ApplySignForm'

