--SERP
begin --帳戶是否停用 SERP
SELECT IS_DISABLE,* FROM RAW_CM_USER
  LEFT OUTER JOIN SYS_USER_MAIN
  ON RAW_CM_USER.USER_ID = SYS_USER_MAIN.USER_ID
WHERE IS_DISABLE IS NULL
end

begin--電子簽核單自動指派後 還原成未指派狀態
UPDATE recm93
   SET rec93_fsts = '2'
     , rec93_fsts1 = '4'
     , rec93_pstfn = ''
 WHERE rec93_form IN ('19100001','19100017', '19100019', '19100020', '19100021', '19100022')

UPDATE recm94
   SET rec94_bsts = NULL
 WHERE rec94_form IN ('19100001','19100017', '19100019', '19100020', '19100021', '19100022') AND rec94_stfn = '002578'

UPDATE message
   SET msg_sts = '0'
   FROM ( select '%19100001%' as c1 union select '%19100017%' as c1 union select '%19100019%' as c1 union select '%19100020%' as c1 union select '%19100021%' as c1 union select '%19100022%' as c1) AS M
 WHERE msg_stfn = '002578' 
   AND msg_message LIKE M.c1 --'%19100020%'

DELETE recm94
WHERE rec94_form IN ('19100001','19100017', '19100019', '19100020', '19100021', '19100022') AND rec94_fsts > '4'
end

begin --清除卡死的EDI流程
BEGIN TRAN
UPDATE EDI_FLOW
   SET STATUS_ID = 'F'
 WHERE SYS_ID = 'XFLAP'
   AND STATUS_ID = 'W' 
   AND EDI_FLOW_ID = 'UpdateProduct'
 --AND EDI_DATE = '' --作業日期
 --AND EDI_TIME = '' --作業時間
 --AND DATA_DATE = '' --資料日期
ROLLBACK
end

begin --API權限驗證 (如果本機呼叫SERVER,IP加到ValidationServerIPAddressString)
DECLARE @API_CN INT = 0; 
DECLARE @CN_CLIENT_SYS_ID INT = 0; 
DECLARE @CN_CLIENT_SYS_IP_ADDRESS INT = 0; 
SELECT @CN_CLIENT_SYS_ID=COUNT(CLIENT_SYS_ID) 
FROM SYS_SYSTEM_API_CLIENT 
WHERE SYS_ID='CTMAP' AND API_CONTROLLER_ID='Subscriber' AND API_ACTION_NAME='ERPAPIspfm00EditEvent'; 

SELECT @CN_CLIENT_SYS_ID
IF @CN_CLIENT_SYS_ID>0 
BEGIN 
    SELECT @CN_CLIENT_SYS_IP_ADDRESS=COUNT(P.IP_ADDRESS) 
    FROM SYS_SYSTEM_API_CLIENT C 
    JOIN SYS_SYSTEM_IP P ON C.CLIENT_SYS_ID=P.SYS_ID 
    WHERE C.SYS_ID='CTMAP' AND C.API_CONTROLLER_ID='Subscriber' AND C.API_ACTION_NAME='ERPAPIspfm00EditEvent' 
      AND C.CLIENT_SYS_ID='ERPAP' AND P.IP_ADDRESS='10.35.2.205'; 

	  SELECT @CN_CLIENT_SYS_IP_ADDRESS
END; 
IF (@CN_CLIENT_SYS_ID>0 AND @CN_CLIENT_SYS_IP_ADDRESS>0) 
BEGIN 
SELECT 'Y'
    SELECT @API_CN=COUNT(A.API_ACTION_NAME) 
    FROM SYS_SYSTEM_API A 
    JOIN SYS_SYSTEM_MAIN M ON A.SYS_ID=M.SYS_ID 
    WHERE A.SYS_ID='CTMAP' AND A.API_CONTROLLER_ID='Subscriber' AND A.API_ACTION_NAME='ERPAPIspfm00EditEvent' 
      AND A.IS_DISABLE='N' AND M.IS_DISABLE='N' 
END; 
SELECT @API_CN; 
end

begin --AP權限驗證 (先檢查IP有沒有在信任IP中)
DECLARE @TRUST_IP_CNT INT;
DECLARE @RESULT CHAR;

SELECT @TRUST_IP_CNT=COUNT(1) 
FROM SYS_TRUST_IP 
WHERE dbo.FN_GET_TRSUT_BYIP(IP_BEGIN, IP_END, '127.0.0.1')='Y'; 
IF @TRUST_IP_CNT > 0 
BEGIN 
    SELECT @RESULT=(CASE WHEN TRUST_STATUS IS NOT NULL THEN TRUST_STATUS ELSE 'N' END) 
    FROM SYS_TRUST_IP 
    WHERE dbo.FN_GET_TRSUT_BYIP(IP_BEGIN, IP_END, '127.0.0.1')='Y'; 
END; 
SELECT @RESULT; 

--如果不是127.0.0.1  在檢查登入者有沒有被限制
--檢查是否允許外部IP

--最後跑這段
DECLARE @IN_BUILDING_CN INT = 0; 
DECLARE @SESSION_ID CHAR(24); 
DECLARE @FUN_CN INT = 0; 
SELECT @IN_BUILDING_CN=COUNT(1) 
FROM SYS_TRUST_IP 
WHERE dbo.FN_GET_TRSUT_BYIP(IP_BEGIN, IP_END, '127.0.0.1')='Y' 
  AND SOURCE_TYPE='C'; 
SELECT TOP 1 @SESSION_ID=C.SESSION_ID 
FROM SYS_USER_CONNECT C 
JOIN SYS_USER_MAIN U ON C.USER_ID=U.USER_ID 
JOIN RAW_CM_USER R ON U.USER_ID=R.USER_ID 
WHERE C.USER_ID='00D223' AND C.SESSION_ID='eoophip5vofy3oqhlcs0zxq0' AND C.CUST_LOGOUT='N' 
  AND C.IP_ADDRESS=(CASE WHEN @IN_BUILDING_CN>0 THEN C.IP_ADDRESS ELSE '127.0.0.1' END) 
  AND U.IS_DISABLE='N' AND R.IS_LEFT='N' 
ORDER BY C.LAST_CONNECT_DT DESC; 
IF @SESSION_ID IS NOT NULL 
BEGIN 
    UPDATE SYS_USER_CONNECT SET 
        LAST_CONNECT_DT=GETDATE(), IP_ADDRESS='127.0.0.1' 
    WHERE USER_ID='00D223' AND SESSION_ID='eoophip5vofy3oqhlcs0zxq0'; 
    SELECT @FUN_CN=COUNT(F.FUN_ACTION_NAME) 
    FROM SYS_USER_SYSTEM_ROLE R 
    JOIN SYS_SYSTEM_ROLE_FUN F ON R.SYS_ID=F.SYS_ID AND R.ROLE_ID=F.ROLE_ID 
    JOIN SYS_SYSTEM_FUN U ON F.SYS_ID=U.SYS_ID AND F.FUN_CONTROLLER_ID=U.FUN_CONTROLLER_ID AND F.FUN_ACTION_NAME=U.FUN_ACTION_NAME 
    JOIN SYS_SYSTEM_MAIN M ON U.SYS_ID=M.SYS_ID 
    WHERE R.USER_ID='00D223' 
      AND F.SYS_ID='ERPAP' AND F.FUN_CONTROLLER_ID='Sys' AND F.FUN_ACTION_NAME='SystemRoleCondition' 
      AND U.IS_DISABLE='N' AND M.IS_DISABLE='N'; 
    IF @FUN_CN=0 
    BEGIN 
        SELECT @FUN_CN=COUNT(U.FUN_ACTION_NAME) 
        FROM SYS_USER_FUN F 
        JOIN SYS_SYSTEM_FUN U ON F.SYS_ID=U.SYS_ID AND F.FUN_CONTROLLER_ID=U.FUN_CONTROLLER_ID AND F.FUN_ACTION_NAME=U.FUN_ACTION_NAME 
        JOIN SYS_SYSTEM_MAIN M ON U.SYS_ID=M.SYS_ID 
        WHERE F.USER_ID='00D223' AND F.IS_ASSIGN='Y' 
          AND F.SYS_ID='ERPAP' AND F.FUN_CONTROLLER_ID='Sys' AND F.FUN_ACTION_NAME='SystemRoleCondition' 
          AND U.IS_DISABLE='N' AND M.IS_DISABLE='N'; 
    END; 
END; 
SELECT @FUN_CN; 
end

begin --員工組織資料
SELECT O.USER_ID AS 員編
     , U.USER_WORK_ID AS ERP工作代碼
	 , CMC.CODE_NM_ZH_TW AS ERP工作名稱
     , O.USER_DEPT AS 部門
	 , CMA.CODE_NM_ZH_TW AS 部門名稱
	 , O.USER_AREA AS 區域
	 , CMD.CODE_NM_ZH_TW AS 區域名稱
	 , O.USER_TEAM AS 組別
	 , CMB.CODE_NM_ZH_TW AS 組別名稱
	 , C.COM_ID AS 公司代碼
	 , C.COM_NM AS 公司名稱
	 , C.COM_COUNTRY AS 公司國家
	 , U.USER_SALARY_COM_ID AS 薪資公司
  FROM RAW_CM_USER U
  JOIN RAW_CM_USER_ORG O
    ON U.USER_ID = O.USER_ID
  JOIN RAW_CM_ORG_COM C
    ON C.COM_ID = U.USER_COM_ID
  JOIN RAW_CM_ORG_COM SC
    ON SC.IS_SALARY_COM = 'Y'
   AND SC.COM_ID = U.USER_COM_ID
   JOIN CM_CODE AS CMA--部門
     ON CMA.CODE_KIND = '0018'
	AND CMA.CODE_ID = O.USER_DEPT
  JOIN CM_CODE AS CMB--組別
     ON CMB.CODE_KIND = '0019'
	AND CMB.CODE_ID = O.USER_TEAM
   JOIN CM_CODE AS CMC--工作
     ON CMC.CODE_KIND = '0038'
	AND CMC.CODE_ID = U.USER_WORK_ID
   JOIN CM_CODE AS CMD--區域
     ON CMD.CODE_KIND = '0015'
	AND CMD.CODE_ID = O.USER_AREA
 WHERE U.USER_ID = '00D223'
 end

begin --使用者擁有功能(角色和功能)
SELECT * FROM SYS_SYSTEM_FUN_MENU --選單大項目(功能選單)
WHERE SYS_ID = 'ERPAP'

SELECT * FROM SYS_USER_FUN_MENU --使用者有的功能選單
WHERE USER_ID = '00D223'
AND SYS_ID = 'ERPAP'

SELECT * FROM SYS_SYSTEM_MENU_FUN --有被設定到選單上的功能(menu有列出可點選的)
WHERE SYS_ID = 'ERPAP'

SELECT * FROM SYS_USER_FUN --選單細項(使用者有的選單功能 menu有列出可點選的)
WHERE USER_ID = '00D223'
  AND SYS_ID = 'ERPAP' AND FUN_CONTROLLER_ID = 'Sys'

SELECT * FROM SYS_SYSTEM_FUN ssf --所有的功能(全部controller action)
WHERE ssf.SYS_ID = 'ERPAP'

SELECT * FROM SYS_USER_SYSTEM_ROLE susr --人有什麼角色
WHERE susr.USER_ID = '00D223'
AND susr.SYS_ID = 'LXSCNAP'

SELECT * FROM SYS_SYSTEM_ROLE_FUN --角色有什麼功能
WHERE SYS_ID = 'ERPAP'

--人有什麼功能(全部controller action)
SELECT MF.FUN_MENU
     , FMM.FUN_MENU_NM_ZH_TW
     , F.SYS_ID
     , F.ROLE_ID
	 , F.FUN_CONTROLLER_ID
	 , F.FUN_ACTION_NAME
	 , SF.FUN_NM_ZH_TW
  FROM SYS_USER_SYSTEM_ROLE R --人有什麼角色
  JOIN SYS_SYSTEM_ROLE_FUN F --角色有什麼功能
    ON F.SYS_ID = R.SYS_ID
   AND F.ROLE_ID = R.ROLE_ID
  JOIN SYS_SYSTEM_FUN SF --所有功能 取功能名稱
    ON F.SYS_ID = SF.SYS_ID
   AND F.FUN_CONTROLLER_ID = SF.FUN_CONTROLLER_ID
   AND F.FUN_ACTION_NAME = SF.FUN_ACTION_NAME
  LEFT JOIN SYS_SYSTEM_MENU_FUN MF --功能在MENU的哪一大類
    ON MF.SYS_ID = F.SYS_ID
   AND MF.FUN_CONTROLLER_ID = F.FUN_CONTROLLER_ID
   AND MF.FUN_ACTION_NAME = F.FUN_ACTION_NAME
  LEFT JOIN SYS_SYSTEM_FUN_MENU FMM --取大分類的名字
    ON FMM.FUN_MENU = MF.FUN_MENU
   AND FMM.SYS_ID = MF.SYS_ID 
 WHERE R.USER_ID = '00D223'
   AND F.SYS_ID = 'ERPAP'
end

--ERP
begin --查詢帳號密碼
SELECT * FROM opagm20
WHERE stfn_stfn IN ('00D290','008382','00D223','008877','00D470','002578')
end
