--//////////////////////////SERP////////////////////////////////////
--帳戶是否停用 SERP
SELECT IS_DISABLE,* FROM RAW_CM_USER
  LEFT OUTER JOIN SYS_USER_MAIN
  ON RAW_CM_USER.USER_ID = SYS_USER_MAIN.USER_ID
WHERE IS_DISABLE IS NULL

--清除卡死的EDI流程
BEGIN TRAN
UPDATE EDI_FLOW
   SET STATUS_ID = 'F'
   WHERE SYS_ID = 'XFLAP'
  AND STATUS_ID = 'W' 
  AND EDI_FLOW_ID = 'UpdateProduct'
AND EDI_DATE = '' --作業日期
AND EDI_TIME = '' --作業時間
AND DATA_DATE = '' --資料日期
ROLLBACK

--API權限驗證
DECLARE @API_CN INT = 0; 
DECLARE @CN_CLIENT_SYS_ID INT = 0; 
DECLARE @CN_CLIENT_SYS_IP_ADDRESS INT = 0; 
SELECT @CN_CLIENT_SYS_ID=COUNT(CLIENT_SYS_ID) 
FROM SYS_SYSTEM_API_CLIENT 
WHERE SYS_ID='CTMAP' AND API_CONTROLLER_ID='Subscriber' AND API_ACTION_NAME='ERPAPIspfm00EditEvent'; 

SELECT @CN_CLIENT_SYS_ID
IF @CN_CLIENT_SYS_ID>0 
BEGIN 
    SELECT @CN_CLIENT_SYS_IP_ADDRESS=COUNT(P.IP_ADDRESS) 
    FROM SYS_SYSTEM_API_CLIENT C 
    JOIN SYS_SYSTEM_IP P ON C.CLIENT_SYS_ID=P.SYS_ID 
    WHERE C.SYS_ID='CTMAP' AND C.API_CONTROLLER_ID='Subscriber' AND C.API_ACTION_NAME='ERPAPIspfm00EditEvent' 
      AND C.CLIENT_SYS_ID='ERPAP' AND P.IP_ADDRESS='10.35.2.205'; 

	  SELECT @CN_CLIENT_SYS_IP_ADDRESS
END; 
IF (@CN_CLIENT_SYS_ID>0 AND @CN_CLIENT_SYS_IP_ADDRESS>0) 
BEGIN 
SELECT 'Y'
    SELECT @API_CN=COUNT(A.API_ACTION_NAME) 
    FROM SYS_SYSTEM_API A 
    JOIN SYS_SYSTEM_MAIN M ON A.SYS_ID=M.SYS_ID 
    WHERE A.SYS_ID='CTMAP' AND A.API_CONTROLLER_ID='Subscriber' AND A.API_ACTION_NAME='ERPAPIspfm00EditEvent' 
      AND A.IS_DISABLE='N' AND M.IS_DISABLE='N' 
END; 
SELECT @API_CN; 

--AP權限驗證
DECLARE @IN_BUILDING_CN INT = 0; 
DECLARE @SESSION_ID CHAR(24); 
DECLARE @FUN_CN INT = 0; 
SELECT @IN_BUILDING_CN=COUNT(1) 
FROM SYS_TRUST_IP 
WHERE dbo.FN_GET_TRSUT_BYIP(IP_BEGIN, IP_END, '127.0.0.1')='Y' 
  AND SOURCE_TYPE='C'; 
SELECT TOP 1 @SESSION_ID=C.SESSION_ID 
FROM SYS_USER_CONNECT C 
JOIN SYS_USER_MAIN U ON C.USER_ID=U.USER_ID 
JOIN RAW_CM_USER R ON U.USER_ID=R.USER_ID 
WHERE C.USER_ID='00D223' AND C.SESSION_ID='eoophip5vofy3oqhlcs0zxq0' AND C.CUST_LOGOUT='N' 
  AND C.IP_ADDRESS=(CASE WHEN @IN_BUILDING_CN>0 THEN C.IP_ADDRESS ELSE '127.0.0.1' END) 
  AND U.IS_DISABLE='N' AND R.IS_LEFT='N' 
ORDER BY C.LAST_CONNECT_DT DESC; 
IF @SESSION_ID IS NOT NULL 
BEGIN 
    UPDATE SYS_USER_CONNECT SET 
        LAST_CONNECT_DT=GETDATE(), IP_ADDRESS='127.0.0.1' 
    WHERE USER_ID='00D223' AND SESSION_ID='eoophip5vofy3oqhlcs0zxq0'; 
    SELECT @FUN_CN=COUNT(F.FUN_ACTION_NAME) 
    FROM SYS_USER_SYSTEM_ROLE R 
    JOIN SYS_SYSTEM_ROLE_FUN F ON R.SYS_ID=F.SYS_ID AND R.ROLE_ID=F.ROLE_ID 
    JOIN SYS_SYSTEM_FUN U ON F.SYS_ID=U.SYS_ID AND F.FUN_CONTROLLER_ID=U.FUN_CONTROLLER_ID AND F.FUN_ACTION_NAME=U.FUN_ACTION_NAME 
    JOIN SYS_SYSTEM_MAIN M ON U.SYS_ID=M.SYS_ID 
    WHERE R.USER_ID='00D223' 
      AND F.SYS_ID='ERPAP' AND F.FUN_CONTROLLER_ID='Sys' AND F.FUN_ACTION_NAME='SystemRoleCondition' 
      AND U.IS_DISABLE='N' AND M.IS_DISABLE='N'; 
    IF @FUN_CN=0 
    BEGIN 
        SELECT @FUN_CN=COUNT(U.FUN_ACTION_NAME) 
        FROM SYS_USER_FUN F 
        JOIN SYS_SYSTEM_FUN U ON F.SYS_ID=U.SYS_ID AND F.FUN_CONTROLLER_ID=U.FUN_CONTROLLER_ID AND F.FUN_ACTION_NAME=U.FUN_ACTION_NAME 
        JOIN SYS_SYSTEM_MAIN M ON U.SYS_ID=M.SYS_ID 
        WHERE F.USER_ID='00D223' AND F.IS_ASSIGN='Y' 
          AND F.SYS_ID='ERPAP' AND F.FUN_CONTROLLER_ID='Sys' AND F.FUN_ACTION_NAME='SystemRoleCondition' 
          AND U.IS_DISABLE='N' AND M.IS_DISABLE='N'; 
    END; 
END; 
SELECT @FUN_CN; 


--//////////////////////////ERP////////////////////////////////////
-- 查詢帳號密碼 --
SELECT * FROM opagm20
WHERE stfn_stfn IN ('00D290','008382','00D223','008877','00D470','002578')

